version: "3.9"
#NETWORK
networks:
  app-network:
    driver: bridge

#VOL
volumes:
  dir_site:

services:
  #PHP
  app-php:
    container_name: php-product
    build:
      dockerfile: Dockerfile
      context: ./import/php
    hostname: php
    restart: always
    networks:
      - app-network
    volumes:
      - ./source:/home/sites/main
      - ./import/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./import/php/php.ini:/usr/local/etc/php/php.ini

  #HTTPS
  app-httpd:
    container_name: ${PROJECT_NAME}_www
    image: "httpd:latest"
    hostname: httpd
    restart: always
    networks:
      - app-network
    volumes:
      - ./source:/home/sites/main
      - ./import/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "${NGINX_PORT}" # http://localhost:9999
      - "443:443"

  #MYSQL
  app-mysql:
    container_name: ${PROJECT_NAME}_db
    image: "mariadb:10.5.12"
    hostname: "mysql"
    restart: always
    networks:
      - app-network
    volumes:
      - ./import/mysql/db:/var/lib/mysql
      - ./import/mysql/my.conf:/etc/mysql/my.conf
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
